# Main sops config
keys:
  # ---------------------------------------------------------------
  # 👤 Users (Admins)
  # ---------------------------------------------------------------
  - &krit age1qxyp5wzwhjs4tq633gtg2d25czdgwf6rxuppasshgf4mhlu37etq909x6t

  # ---------------------------------------------------------------
  # 🖥️ Hosts (Machines)
  # ---------------------------------------------------------------
  - &nixos-desktop age1nvr3ges07kcl6h4lmmfl23lc07rl7njq9seyl4hp7uut4k8v53qquhfugp
  - &Krits-MacBook-Pro age14q0q9ulmz3shshr7vqfh37w0udz74uyv6xf6uywgavgsqfnf2yhqtyzkcj
  - &nixos-laptop age1lpf8kampchc63sgxsf6j7mscc22tpp93er3peztkyhyjth33ygrslzkz7l

creation_rules:
  # ---------------------------------------------------------------
  # 🔒 Secrets for "nixos-desktop"
  # Any file inside hosts/nixos-desktop/ ending in secrets-sops.yaml will use these keys
  # ---------------------------------------------------------------
  - path_regex: hosts/nixos-desktop/.*secrets-sops\.yaml$
    key_groups:
      - age:
          - *krit # You can decrypt (user "krit")
          - *nixos-desktop # The machine can decrypt (hostname "nixos-desktop")

  # ---------------------------------------------------------------
  # 🔒 Secrets for "nixos-laptop"
  # Any file inside hosts/nixos-laptop/ ending in secrets-sops.yaml will use these keys
  # ---------------------------------------------------------------
  - path_regex: hosts/nixos-laptop/.*secrets-sops\.yaml$
    key_groups:
      - age:
          - *krit # You can decrypt (user "krit")
          - *nixos-laptop # The machine can decrypt (hostname "nixos-desktop")

  # ---------------------------------------------------------------
  # 🔒 Secrets for "Krits-MacBook-Pro"
  # ---------------------------------------------------------------
  - path_regex: hosts/Krits-MacBook-Pro/.*secrets-sops\.yaml$
    key_groups:
      - age:
          - *krit
          - *Krits-MacBook-Pro

  # ---------------------------------------------------------------
  # 🔒 Common rules for user "krit"
  # Matches any "krit-common-secrets-sops.yaml" inside the "common" folder
  # ---------------------------------------------------------------
  - path_regex: users/krit/common/sops/krit-common-secrets-sops.yaml$
    key_groups:
      - age:
          - *krit # You can decrypt (user krit)
          - *nixos-desktop # Desktop (nixos-desktop)
          - *nixos-laptop # Laptop (nixos-laptop)
          - *Krits-MacBook-Pro # Laptop (nix-darwin)

  # 🔒 (Example) Rules for a future host
  # ---------------------------------------------------------------
  # ---------------------------------------------------------------
  # - path_regex: hosts/francesco-desktop/.*secrets\.yaml$
  #   key_groups:
  #     - age:
  #         - *francesco
  #         - *francesco-desktop
